version: '3.8'

services:
  register:
    image: ghcr.io/tomacheese/niconico-timeshift-register:v1.0.0
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./config.json
        target: /app/config.json
    restart: always

  downloader:
    image: ghcr.io/tomacheese/niconico-timeshift-downloader:v1.0.0
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./config.json
        target: /app/config.json
    restart: always
